[package]
name = "dht22"
version = "0.1.0"
edition = "2021"

[dependencies]
simple-logging = "2.0.2"
simple_logger = "5.0.0"
dht22_pi = "1.0.0"
rppal = "0.22.1" # Check the rppal documentation for the latest version
libc = "0.2.178"
log = "0.4"

